using CSBS101._82Application.ExtensionsMethods.BB00X;
using CSBS101._82Application.Mapper.AA00X.AA013;
using CSBS101._82Application.Mapper.AA00X.AA027;
using CSBS101._82Application.Mapper.BB00X;
using CSBS101._82Application.Mapper.BB00X.BB00X.BB001;
using CSBS101._82Application.Mapper.BB00X.BB012;
using CSCore.Application.Dto.Dtos.DD.DD00X.DD000;
using CSCore.Application.Dto.Mapper.FF.FF00X;
using CSCore.Application.Dto.Mapper.GG00X;
using CSCore.Domain.CS_Models.CSICP_DD;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSCore.Application.Dto.Mapper.DD
{
    public static class DD000Mapper
    {
        public static DtoGetDD000 ToDtoGetDD000(this CSICP_DD000 entity)
        {
            return new DtoGetDD000
            {
                TenantId = entity.TenantId,
                Dd000ConfigId = entity.Dd000ConfigId,
                Dd000FilialId = entity.Dd000FilialId,
                Dd000PvCcustoId = entity.Dd000PvCcustoId,
                Dd000PvAgcobradorId = entity.Dd000PvAgcobradorId,
                Dd000PvNatoperacaoId = entity.Dd000PvNatoperacaoId,
                Dd000PvContaId = entity.Dd000PvContaId,
                Dd000CtrlSerieNfId = entity.Dd000CtrlSerieNfId,
                Dd000CtrlSerieCfId = entity.Dd000CtrlSerieCfId,
                Dd000CtrlSerieNfceId = entity.Dd000CtrlSerieNfceId,
                Dd000PdCcustoId = entity.Dd000PdCcustoId,
                Dd000PdAgcobradorId = entity.Dd000PdAgcobradorId,
                Dd000PdNatoperacaoId = entity.Dd000PdNatoperacaoId,
                Dd000PdvCcustoId = entity.Dd000PdvCcustoId,
                Dd000PdvAgcobradorId = entity.Dd000PdvAgcobradorId,
                Dd000PdvNatoperacaoId = entity.Dd000PdvNatoperacaoId,
                Dd000CtCcustoId = entity.Dd000CtCcustoId,
                Dd000CtAgcobradorId = entity.Dd000CtAgcobradorId,
                Dd000CtNatoperacaoId = entity.Dd000CtNatoperacaoId,
                Dd000Qtddiasvalcotacao = entity.Dd000Qtddiasvalcotacao,
                Dd000Qtddiasvalprevenda = entity.Dd000Qtddiasvalprevenda,
                Dd000Qualregraaplicar = entity.Dd000Qualregraaplicar,
                Dd000AmbNfeId = entity.Dd000AmbNfeId,
                Dd000VersaoNfeId = entity.Dd000VersaoNfeId,
                Dd000LcertdigitalId = entity.Dd000LcertdigitalId,
                //Dd000Arqcertdigitalbinario = entity.Dd000Arqcertdigitalbinario,
                Dd000Arqcertdigital = entity.Dd000Arqcertdigital,
                Dd000Senhacertdigital = entity.Dd000Senhacertdigital,
                Dd000NdCcustoId = entity.Dd000NdCcustoId,
                Dd000NdAgcobradorId = entity.Dd000NdAgcobradorId,
                Dd000NdNatoperacaoId = entity.Dd000NdNatoperacaoId,
                Dd000DcCcustoId = entity.Dd000DcCcustoId,
                Dd000DcAgcobradorId = entity.Dd000DcAgcobradorId,
                Dd000DcNatoperacaoId = entity.Dd000DcNatoperacaoId,
                Dd000DisCcustoId = entity.Dd000DisCcustoId,
                Dd000DisAgcobradorId = entity.Dd000DisAgcobradorId,
                Dd000DisNatoperacaoId = entity.Dd000DisNatoperacaoId,
                Dd000ZonetimeId = entity.Dd000ZonetimeId,
                Dd000CpCcustoId = entity.Dd000CpCcustoId,
                Dd000CpAgcobradorId = entity.Dd000CpAgcobradorId,
                Dd000CpCondpagtoId = entity.Dd000CpCondpagtoId,
                Dd000CpFormapagtoId = entity.Dd000CpFormapagtoId,
                Dd000CpDiaVencto = entity.Dd000CpDiaVencto,
                Dd000UfOrgaoId = entity.Dd000UfOrgaoId,
                Dd000Qtddiasvaletiq = entity.Dd000Qtddiasvaletiq,
                Dd000NfeConjugada = entity.Dd000NfeConjugada,
                Dd000OrigPcomissaoId = entity.Dd000OrigPcomissaoId,
                Dd000FormaPcomId = entity.Dd000FormaPcomId,
                Dd000Comespecieid = entity.Dd000Comespecieid,
                Dd000NfsIsmultiplo = entity.Dd000NfsIsmultiplo,
                Dd000NfsPadraoId = entity.Dd000NfsPadraoId,
                Dd000NfsRegesptribId = entity.Dd000NfsRegesptribId,
                Dd000NfsOtpsnId = entity.Dd000NfsOtpsnId,
                Dd000NfsInccultId = entity.Dd000NfsInccultId,
                Dd000NfsCodintegrcliente = entity.Dd000NfsCodintegrcliente,
                Dd000NfsUrlWsInvoicy = entity.Dd000NfsUrlWsInvoicy,
                Dd000NfsAlvaraempresa = entity.Dd000NfsAlvaraempresa,
                Dd000NfsNatop = entity.Dd000NfsNatop,
                Dd000PdvWebRptNfceId = entity.Dd000PdvWebRptNfceId,
                Dd000PdvWebRptNfeId = entity.Dd000PdvWebRptNfeId,
                Dd000PdvWebRptNfId = entity.Dd000PdvWebRptNfId,
                Dd000Tokenacessows = entity.Dd000Tokenacessows,
                Dd000Isenviows = entity.Dd000Isenviows,
                Dd000Isusaambiente = entity.Dd000Isusaambiente,
                Dd000Isusaprojeto = entity.Dd000Isusaprojeto,
                Dd000Vmetadiamonitor = entity.Dd000Vmetadiamonitor,
                Dd000Qmetadiamonitor = entity.Dd000Qmetadiamonitor,
                Dd000Iscomissaogerente = entity.Dd000Iscomissaogerente,
                Dd000Valormincomissao = entity.Dd000Valormincomissao,
                Dd000Exibepvfaturada = entity.Dd000Exibepvfaturada,
                Dd000Isdataemissaooriginal = entity.Dd000Isdataemissaooriginal,
                Dd000RegralimitedescontoId = entity.Dd000RegralimitedescontoId,
                Dd000Vlrmaxarredondvenda = entity.Dd000Vlrmaxarredondvenda,
                Dd000Isusacomanda = entity.Dd000Isusacomanda,
                Dd000Ishabilitapvexpress = entity.Dd000Ishabilitapvexpress,
                Dd000FormapgtId = entity.Dd000FormapgtId,
                Dd000Isusavendareprimida = entity.Dd000Isusavendareprimida,
                Dd000Ishabilitaperfalmox = entity.Dd000Ishabilitaperfalmox,
                Dd000Isvendadeposito = entity.Dd000Isvendadeposito,
                Dd000Ispermitesaldonegativo = entity.Dd000Ispermitesaldonegativo,
                Dd000Iscontigencianfce = entity.Dd000Iscontigencianfce,
                Dd000SatAssinaturaac = entity.Dd000SatAssinaturaac,
                Dd000SatCodigoativacao = entity.Dd000SatCodigoativacao,
                Dd000Almoxpadraotrocaid = entity.Dd000Almoxpadraotrocaid,
                Dd000CtrlContigenciaNfcei = entity.Dd000CtrlContigenciaNfcei,
                Dd000Isusavaloresretido = entity.Dd000Isusavaloresretido,
                Dd000Iscalculavolume = entity.Dd000Iscalculavolume,
                Dd000Tipoimportbibliotec = entity.Dd000Tipoimportbibliotec,
                Dd000Tipoinsercaoprod = entity.Dd000Tipoinsercaoprod,
                Dd000CorreiosUsuario = entity.Dd000CorreiosUsuario,
                Dd000CorreiosSenha = entity.Dd000CorreiosSenha,
                Dd000Urlcorreios = entity.Dd000Urlcorreios,
                Dd000Iscanccomentrega = entity.Dd000Iscanccomentrega,
                NavDD000FormaPcom = entity.NavDD000FormaPcom,
                NavDD000Filial = entity.NavDD000Filial?.ToDtoGetBB001ListSimples(),
                NavDD000PvCcusto = entity.NavDD000PvCcusto?.ToDtoGet(),
                NavDD000PdCcusto = entity.NavDD000PdCcusto?.ToDtoGet(),
                NavDD000PdvCcusto = entity.NavDD000PdvCcusto?.ToDtoGet(),
                NavDD000CtCcusto = entity.NavDD000CtCcusto?.ToDtoGet(),
                NavDD000NdCcusto = entity.NavDD000NdCcusto?.ToDtoGet(),
                NavDD000DcCcusto = entity.NavDD000DcCcusto?.ToDtoGet(),
                NavDD000DisCcusto = entity.NavDD000DisCcusto?.ToDtoGet(),
                NavDD000CpCcusto = entity.NavDD000CpCcusto?.ToDtoGet(),
                NavDD000PvAgcobrador = entity.NavDD000PvAgcobrador?.ToDtoGetExibicao(),
                NavDD000PdAgcobrador = entity.NavDD000PdAgcobrador?.ToDtoGetExibicao(),
                NavDD000PdvAgcobrador = entity.NavDD000PdvAgcobrador?.ToDtoGetExibicao(),
                NavDD000CtAgcobrador = entity.NavDD000CtAgcobrador?.ToDtoGetExibicao(),
                NavDD000NdAgcobrador = entity.NavDD000NdAgcobrador?.ToDtoGetExibicao(),
                NavDD000DcAgcobrador = entity.NavDD000DcAgcobrador?.ToDtoGetExibicao(),
                NavDD000DisAgcobrador = entity.NavDD000DisAgcobrador?.ToDtoGetExibicao(),
                NavDD000CpAgcobrador = entity.NavDD000CpAgcobrador?.ToDtoGetExibicao(),
                NavDD000PvNatoperacao = entity.NavDD000PvNatoperacao?.ToDtoGetSimples(),
                NavDD000PdNatoperacao = entity.NavDD000PdNatoperacao?.ToDtoGetSimples(),
                NavDD000PdvNatoperacao = entity.NavDD000PdvNatoperacao?.ToDtoGetSimples(),
                NavDD000CtNatoperacao = entity.NavDD000CtNatoperacao?.ToDtoGetSimples(),
                NavDD000NdNatoperacao = entity.NavDD000NdNatoperacao?.ToDtoGetSimples(),
                NavDD000DcNatoperacao = entity.NavDD000DcNatoperacao?.ToDtoGetSimples(),
                NavDD000DisNatoperacao = entity.NavDD000DisNatoperacao?.ToDtoGetSimples(),
                NavDD000PvConta = entity.NavDD000PvConta?.ToDtoGetExibSimples(),
                NavDD000CtrlSerieNf = entity.NavDD000CtrlSerieNf?.ToDtoGetAA013_Simples(),
                NavDD000CtrlSerieCf = entity.NavDD000CtrlSerieCf?.ToDtoGetAA013_Simples(),
                NavDD000CtrlSerieNfce = entity.NavDD000CtrlSerieNfce?.ToDtoGetAA013_Simples(),
                NavDD000CtrlContigenciaNfce = entity.NavDD000CtrlContigenciaNfce?.ToDtoGetAA013_Simples(),
                NavDD000CpCondpagto = entity.NavDD000CpCondpagto?.ToDtoGetSimples(),
                NavDD000CpFormapagto = entity.NavDD000CpFormapagto?.ToDtoGetExibicao(),
                NavDD000Formapgt = entity.NavDD000Formapgt?.ToDtoGetExibicao(),
                NavDD000UfOrgao = entity.NavDD000UfOrgao?.ToDtoGetAA027SASimples(),
                NavDD000ComEspecie = entity.NavDD000ComEspecie?.ToDtoGetExibicao(),
                NavDD000AlmoxPadraoTroca = entity.NavDD000AlmoxPadraoTroca?.ToDtoGetSimples(),
                NavDD000QualRegraAplicar = entity.NavDD000QualRegraAplicar,
                NavDD000AmbNfe = entity.NavDD000AmbNfe,
                NavDD000VersaoNfe = entity.NavDD000VersaoNfe,
                NavDD000LcertDigital = entity.NavDD000LcertDigital,
                NavDD000ZoneTime = entity.NavDD000ZoneTime,
                NavDD000OrigPcomissao = entity.NavDD000OrigPcomissao,
                NavDD000NfsPadrao = entity.NavDD000NfsPadrao,
                NavDD000NfsRegEspTrib = entity.NavDD000NfsRegEspTrib,
                NavDD000NfsOtpSN = entity.NavDD000NfsOtpSN,
                NavDD000NfsIncCult = entity.NavDD000NfsIncCult,
                NavDD000NfsNatOp = entity.NavDD000NfsNatOp,
                NavDD000RegraLimiteDesconto = entity.NavDD000RegraLimiteDesconto
            };
        }
    }
}
