namespace CSCore.RabbitMQ.Hub.Ax
{
    public static class HubGroupNames
    {
        public static string BANCO_BRASIL_HUB_GRUPO = "BANCO_BRASIL_HUB_GRUPO";
        public static string FINANCEIRO_CONTAS_A_PAGAR = "FINANCEIRO_CONTAS_A_PAGAR";
        public static string FINANCEIRO_AGENDA_COBRANCA = "FINANCEIRO_AGENDA_COBRANCA";
        public static string FINANCEIRO_REQUISICAO_DESPESA = "FINANCEIRO_REQUISICAO_DESPESA";
        public static string FINANCEIRO_PROCESSOS = "FINANCEIRO_PROCESSOS";
        public static string FINANCEIRO_PROCESSOS_CG = "FINANCEIRO_PROCESSOS_CG";
    }

    public static class HubMethodNames
    {
        public static string PROCESSAR_BAIXA_ESTOQUE_GG073 = "PROCESSAR_BAIXA_ESTOQUE_GG073";
        public static string BLOQUEAR_DESBLOQUEAR_INVENTARIO_GG032 = "BLOQUEAR_DESBLOQUEAR_INVENTARIO_GG032";
        public static string ANALISE_CREDITO = "ANALISE_CREDITO";
        public static string GERA_PROTOCOLO_CI = "GERA_PROTOCOLO_CI";
        public static string AJUSTE_PRECO_GG031 = "AJUSTE_PRECO_GG031";
        public static string GERA_INVENTARIO_GG054 = "GERA_INVENTARIO_GG054";
        public static string PROCESSA_BAIXA_GG071 = "PROCESSA_BAIXA_GG071";
        public static string PROCESSAR_INVENTARIO_GG032 = "PROCESSAR_INVENTARIO_GG032";
        public static string GERAR_INVENTARIO_EM_MASSA_GG032 = "GERAR_INVENTARIO_EM_MASSA_GG032";

        //FINANCEIRO
        public static string FINANCEIRO_CONTAS_A_PAGAR_PROCESSAR_CARTA_DEBITO = "FINANCEIRO_CONTAS_A_PAGAR_PROCESSAR_CARTA_DEBITO";
        public static string FINANCEIRO_AGENDA_COBRANCA_PREVISAO_GERAL = "FINANCEIRO_AGENDA_COBRANCA_PREVISAO_GERAL";
        public static string FINANCEIRO_PROCESSOS_GERA_MEMORIA_CALCULO = "FINANCEIRO_PROCESSOS_GERA_MEMORIA_CALCULO";
        public static string FINANCEIRO_PROCESSOS_MVTO_BAIXA_TITULO_KERNEL = "FINANCEIRO_PROCESSOS_MVTO_BAIXA_TITULO_KERNEL";
        public static string FINANCEIRO_PROCESSOS_CALCULO_SIMULACAO_RENEGOCIACAO = "FINANCEIRO_PROCESSOS_CALCULO_SIMULACAO_RENEGOCIACAO";
        public static string FINANCEIRO_PROCESSOS_Cria_Titulo = "FINANCEIRO_PROCESSOS_Cria_Titulo";
        public static string FINANCEIRO_REQUISICAO_DESPESA_GERAR_CONTAS_PAGAR = "FINANCEIRO_REQUISICAO_DESPESA_GERAR_CONTAS_PAGAR";
        public static string FINANCEIRO_CG_ATUALIZA_SALDO_CONTABIL_MES = "FINANCEIRO_CG_ATUALIZA_SALDO_CONTABIL_MES";
    }
}
