using CSBS101._82Application.Mapper.BB00X;
using CSBS101._82Application.Mapper.BB00X.BB003;
using CSBS101._82Application.Mapper.BB00X.BB00X.BB001;
using CSBS101._82Application.Mapper.BB00X.BB012;
using CSCore.Application.Dto.Dtos.Materiais_GG.GG00X.GG008.GG008Kdx;
using CSCore.Application.Dto.Mapper.GG00X;
using CSCore.Domain.CS_Models.Staticas.GG;
using FF105Financeiro.C82Application.Dto.GG00X.GG008.GG008Kdx;

namespace FF105Financeiro.C82Application.Mapper.GG008
{
    public static class GG008KdxMapper
    {
        public static DtoGetGG008Kdx ToDtoGet(this CSICP_GG008Kdx entity)
        {
            return new DtoGetGG008Kdx
            {
                TenantId = entity.TenantId,
                Gg008Kardexid = entity.Gg008Kardexid,
                Gg008Filialid = entity.Gg008Filialid,
                Gg008Produtoid = entity.Gg008Produtoid,
                Gg008Codalmoxpadrao = entity.Gg008Codalmoxpadrao,
                Gg008Codalmtransf = entity.Gg008Codalmtransf,
                Gg008Almoxpadraoid = entity.Gg008Almoxpadraoid,
                Gg008Almoxtransfid = entity.Gg008Almoxtransfid,
                Gg008Unidade = entity.Gg008Unidade,
                Gg008Unidsecundaria = entity.Gg008Unidsecundaria,
                Gg008Unvendavarejoid = entity.Gg008Unvendavarejoid,
                Gg008Uncompravarejoid = entity.Gg008Uncompravarejoid,
                Gg008Unvendaatacadoid = entity.Gg008Unvendaatacadoid,
                Gg008FatorConversao = entity.Gg008FatorConversao,
                Gg008AliquotaIpi = entity.Gg008AliquotaIpi,
                Gg008AliquotaIcms = entity.Gg008AliquotaIcms,
                Gg008AliqIcmsReduzidaPdv = entity.Gg008AliqIcmsReduzidaPdv,
                Gg008AliquotaIss = entity.Gg008AliquotaIss,
                Gg008Margemlucrosai = entity.Gg008Margemlucrosai,
                Gg008Margemlucroent = entity.Gg008Margemlucroent,
                Gg008CalculaIrrf = entity.Gg008CalculaIrrf,
                Gg008CalculaInss = entity.Gg008CalculaInss,
                Gg008PercCsll = entity.Gg008PercCsll,
                Gg008PercCofins = entity.Gg008PercCofins,
                Gg008PercPis = entity.Gg008PercPis,
                Gg008IcmsPauta = entity.Gg008IcmsPauta,
                Gg008IpiPauta = entity.Gg008IpiPauta,
                Gg008Qtdpedidocompra = entity.Gg008Qtdpedidocompra,
                Gg008EstoqueMinimo = entity.Gg008EstoqueMinimo,
                Gg008EstoqueMaximo = entity.Gg008EstoqueMaximo,
                Gg008TempoReposicao = entity.Gg008TempoReposicao,
                Gg008PontoPedido = entity.Gg008PontoPedido,
                Gg008LoteEconomico = entity.Gg008LoteEconomico,
                Gg008GrauAtendimento = entity.Gg008GrauAtendimento,
                Gg008PercTolerancia = entity.Gg008PercTolerancia,
                Gg008Abc = entity.Gg008Abc,
                Gg008PercComissao = entity.Gg008PercComissao,
                Gg008DataFabricacao = entity.Gg008DataFabricacao,
                Gg008DataValidade = entity.Gg008DataValidade,
                Gg008DiasValidade = entity.Gg008DiasValidade,
                Gg008CustoMedio = entity.Gg008CustoMedio,
                Gg008PrecoReposicao = entity.Gg008PrecoReposicao,
                Gg008PercDescItem = entity.Gg008PercDescItem,
                Gg008Prcpromocional = entity.Gg008Prcpromocional,
                Gg008QtdPromocional = entity.Gg008QtdPromocional,
                Gg008FatorLucro = entity.Gg008FatorLucro,
                Gg008PrcVendavarejo = entity.Gg008PrcVendavarejo,
                Gg008PrcVndMercado = entity.Gg008PrcVndMercado,
                Gg008Ultreajprcvenda = entity.Gg008Ultreajprcvenda,
                Gg008PrecoVendaLiq = entity.Gg008PrecoVendaLiq,
                Gg008Vlrmargemlucro = entity.Gg008Vlrmargemlucro,
                Gg008Alteraprcvenda = entity.Gg008Alteraprcvenda,
                Gg008PrecoCusto = entity.Gg008PrecoCusto,
                Gg008Ultreajprccusto = entity.Gg008Ultreajprccusto,
                Gg008PrecoCustoReal = entity.Gg008PrecoCustoReal,
                Gg008CentroCusto = entity.Gg008CentroCusto,
                Gg008Ccustoid = entity.Gg008Ccustoid,
                Gg008ContaContabil = entity.Gg008ContaContabil,
                Gg008ClasseContabil = entity.Gg008ClasseContabil,
                Gg008FornecedorCanal = entity.Gg008FornecedorCanal,
                Gg008Fornecedorpadrao = entity.Gg008Fornecedorpadrao,
                Gg008Contaid = entity.Gg008Contaid,
                Gg008Periodicidadeinv = entity.Gg008Periodicidadeinv,
                Gg008ControlaSaldo = entity.Gg008ControlaSaldo,
                Gg008ControleLote = entity.Gg008ControleLote,
                Gg008ControleGrade = entity.Gg008ControleGrade,
                Gg008Anuente = entity.Gg008Anuente,
                Gg008Restricao = entity.Gg008Restricao,
                Gg008Grupocomprasid = entity.Gg008Grupocomprasid,
                Gg008Permsldnegativo = entity.Gg008Permsldnegativo,
                Gg008Minutaautomatica = entity.Gg008Minutaautomatica,
                Gg008Requisautomatica = entity.Gg008Requisautomatica,
                Gg008DataDesativacao = entity.Gg008DataDesativacao,
                Gg008Localizfixa = entity.Gg008Localizfixa,
                Gg008Diversos = entity.Gg008Diversos,
                Gg008AliqDifPis = entity.Gg008AliqDifPis,
                Gg008AliqDifCofins = entity.Gg008AliqDifCofins,
                Gg008EanTributavel = entity.Gg008EanTributavel,
                Gg008Untributavelid = entity.Gg008Untributavelid,
                Gg008FatorUnidade = entity.Gg008FatorUnidade,
                Gg008ValorPis = entity.Gg008ValorPis,
                Gg008ValorCofins = entity.Gg008ValorCofins,
                Gg008IsActive = entity.Gg008IsActive,
                Gg008TipoConversaoId = entity.Gg008TipoConversaoId,
                Gg008TipoprazoId = entity.Gg008TipoprazoId,
                Gg008TpContribuicaoId = entity.Gg008TpContribuicaoId,
                Gg008RiControlequalidade = entity.Gg008RiControlequalidade,
                Gg008AliquotaIrpj = entity.Gg008AliquotaIrpj,
                Gg008RetencaoAliqInss = entity.Gg008RetencaoAliqInss,
                Gg008RetencaoAliqIrrf = entity.Gg008RetencaoAliqIrrf,
                Gg008DescontoSuframa = entity.Gg008DescontoSuframa,
                Gg008Timestamp = entity.Gg008Timestamp,
                Gg008Plucro = entity.Gg008Plucro,
                Gg008IsctrlGondola = entity.Gg008IsctrlGondola,
                Gg008Qmediaconsumo = entity.Gg008Qmediaconsumo,
                Gg008Vmediaconsumo = entity.Gg008Vmediaconsumo,
                Gg008Dtultprocle = entity.Gg008Dtultprocle,
                Gg008VuncompraCmedio = entity.Gg008VuncompraCmedio,
                Gg008VuncompraReposicao = entity.Gg008VuncompraReposicao,
                Gg008VuncompraPrcvenda = entity.Gg008VuncompraPrcvenda,
                Gg008VuncompraPrcmercado = entity.Gg008VuncompraPrcmercado,
                Gg008VuncompraPrccusto = entity.Gg008VuncompraPrccusto,
                Gg008VuncompraCustoreal = entity.Gg008VuncompraCustoreal,
                Gg008VuncompraVlrmarglucro = entity.Gg008VuncompraVlrmarglucro,
                Gg008Moedaid = entity.Gg008Moedaid,
                Gg008Vmoeda = entity.Gg008Vmoeda,
                Gg008Prcecommerce = entity.Gg008Prcecommerce,
                Gg008Auditasn = entity.Gg008Auditasn,
                Gg008Possuisaldo = entity.Gg008Possuisaldo,
                Gg008Ultrecebimento = entity.Gg008Ultrecebimento,
                Gg008Qtdultrecebto = entity.Gg008Qtdultrecebto,
                Gg008UltimaVenda = entity.Gg008UltimaVenda,
                Gg008QtdeUltVenda = entity.Gg008QtdeUltVenda,
                Gg008TpcbarratribId = entity.Gg008TpcbarratribId,
                NavGG008pOutrosPrecos = entity.NavGG008pOutrosPrecos?.ToDtoGet(),
                NavGG008Produto = entity.NavGG008Produto?.ToDtoGetSimples(),
                NavGG001AlmoxarifadoPadrao = entity.NavGG001AlmoxarifadoPadrao?.ToDtoGetSimples(),
                NavGG001AlmoxarifadoTransferencia = entity.NavGG001AlmoxarifadoTransferencia?.ToDtoGetSimples(),
                NavGG007UNVendaVarejo = entity.NavGG007UNVendaVarejo?.ToDtoGetSimples(),
                NavGG007UNCompraVarejo = entity.NavGG007UNCompraVarejo?.ToDtoGetSimples(),
                NavGG007UNVendaAtacado = entity.NavGG007UNVendaAtacado?.ToDtoGetSimples(),
                NavGG007UNTributavel = entity.NavGG007UNTributavel?.ToDtoGetSimples(),
                NavBB005_CCusto = entity.NavBB005_CCusto?.ToDtoGet(),
                NavBB003_Moeda = entity.NavBB003_Moeda?.ToDtoGet(),
                NavBB012_Conta = entity.NavBB012_Conta?.ToDtoBB012Simples(),
                NavBB001Filial = entity.NavBB001Filial?.ToDtoGetSimples(),
                NavGG008_Tipo_Conversao = entity.NavGG008_Tipo_Conversao,
                NavGG008_TipoPrazo = entity.NavGG008_TipoPrazo,
                NavGG019_tpCBarraTrib = entity.NavGG019_tpCBarraTrib,
                NavGG008_Tp_Contribuicao = entity.NavGG008_Tp_Contribuicao,
                NavGG008_AuditaSN = entity.NavGG008_AuditaSN,
                NavGG008_Desconto_SUFRAMA = entity.NavGG008_Desconto_SUFRAMA,
                NavGG008_Calcula_IRRF = entity.NavGG008_Calcula_IRRF,
                NavGG008_Calcula_INSS = entity.NavGG008_Calcula_INSS,
                NavGG008_AlteraPrcVenda = entity.NavGG008_AlteraPrcVenda,
                NavGG008_Fornecedor_Canal = entity.NavGG008_Fornecedor_Canal,
                NavGG008_Controla_Saldo = entity.NavGG008_Controla_Saldo,
                NavGG008_Controle_Lote = entity.NavGG008_Controle_Lote,
                NavGG008_Controle_Grade = entity.NavGG008_Controle_Grade,
                NavGG008_Anuente = entity.NavGG008_Anuente,
                NavGG008_Restricao = entity.NavGG008_Restricao,
                NavGG008_PermSldNegativo = entity.NavGG008_PermSldNegativo,
                NavGG008_MinutaAutomatica = entity.NavGG008_MinutaAutomatica,
                NavGG008_RequisAutomatica = entity.NavGG008_RequisAutomatica,
            };
        }

        public static DtoGetGG008Kdx_Exibicao ToDtoGetExibicao(this CSICP_GG008Kdx entity)
        {
            return new DtoGetGG008Kdx_Exibicao
            {
                TenantId = entity.TenantId,
                Gg008Kardexid = entity.Gg008Kardexid,
                Gg008Filialid = entity.Gg008Filialid,
                Gg008Produtoid = entity.Gg008Produtoid,
                Gg008Codalmoxpadrao = entity.Gg008Codalmoxpadrao,
                Gg008Codalmtransf = entity.Gg008Codalmtransf,
                Gg008Almoxpadraoid = entity.Gg008Almoxpadraoid,
                Gg008Almoxtransfid = entity.Gg008Almoxtransfid,
                Gg008Unidade = entity.Gg008Unidade,
                Gg008Unidsecundaria = entity.Gg008Unidsecundaria,
                Gg008Unvendavarejoid = entity.Gg008Unvendavarejoid,
                Gg008Uncompravarejoid = entity.Gg008Uncompravarejoid,
                Gg008Unvendaatacadoid = entity.Gg008Unvendaatacadoid,
                Gg008FatorConversao = entity.Gg008FatorConversao,
                Gg008AliquotaIpi = entity.Gg008AliquotaIpi,
                Gg008AliquotaIcms = entity.Gg008AliquotaIcms,
                Gg008AliqIcmsReduzidaPdv = entity.Gg008AliqIcmsReduzidaPdv,
                Gg008AliquotaIss = entity.Gg008AliquotaIss,
                Gg008Margemlucrosai = entity.Gg008Margemlucrosai,
                Gg008Margemlucroent = entity.Gg008Margemlucroent,
                Gg008CalculaIrrf = entity.Gg008CalculaIrrf,
                Gg008CalculaInss = entity.Gg008CalculaInss,
                Gg008PercCsll = entity.Gg008PercCsll,
                Gg008PercCofins = entity.Gg008PercCofins,
                Gg008PercPis = entity.Gg008PercPis,
                Gg008IcmsPauta = entity.Gg008IcmsPauta,
                Gg008IpiPauta = entity.Gg008IpiPauta,
                Gg008Qtdpedidocompra = entity.Gg008Qtdpedidocompra,
                Gg008EstoqueMinimo = entity.Gg008EstoqueMinimo,
                Gg008EstoqueMaximo = entity.Gg008EstoqueMaximo,
                Gg008TempoReposicao = entity.Gg008TempoReposicao,
                Gg008PontoPedido = entity.Gg008PontoPedido,
                Gg008LoteEconomico = entity.Gg008LoteEconomico,
                Gg008GrauAtendimento = entity.Gg008GrauAtendimento,
                Gg008PercTolerancia = entity.Gg008PercTolerancia,
                Gg008Abc = entity.Gg008Abc,
                Gg008PercComissao = entity.Gg008PercComissao,
                Gg008DataFabricacao = entity.Gg008DataFabricacao,
                Gg008DataValidade = entity.Gg008DataValidade,
                Gg008DiasValidade = entity.Gg008DiasValidade,
                Gg008CustoMedio = entity.Gg008CustoMedio,
                Gg008PrecoReposicao = entity.Gg008PrecoReposicao,
                Gg008PercDescItem = entity.Gg008PercDescItem,
                Gg008Prcpromocional = entity.Gg008Prcpromocional,
                Gg008QtdPromocional = entity.Gg008QtdPromocional,
                Gg008FatorLucro = entity.Gg008FatorLucro,
                Gg008PrcVendavarejo = entity.Gg008PrcVendavarejo,
                Gg008PrcVndMercado = entity.Gg008PrcVndMercado,
                Gg008Ultreajprcvenda = entity.Gg008Ultreajprcvenda,
                Gg008PrecoVendaLiq = entity.Gg008PrecoVendaLiq,
                Gg008Vlrmargemlucro = entity.Gg008Vlrmargemlucro,
                Gg008Alteraprcvenda = entity.Gg008Alteraprcvenda,
                Gg008PrecoCusto = entity.Gg008PrecoCusto,
                Gg008Ultreajprccusto = entity.Gg008Ultreajprccusto,
                Gg008PrecoCustoReal = entity.Gg008PrecoCustoReal,
                Gg008CentroCusto = entity.Gg008CentroCusto,
                Gg008Ccustoid = entity.Gg008Ccustoid,
                Gg008ContaContabil = entity.Gg008ContaContabil,
                Gg008ClasseContabil = entity.Gg008ClasseContabil,
                Gg008FornecedorCanal = entity.Gg008FornecedorCanal,
                Gg008Fornecedorpadrao = entity.Gg008Fornecedorpadrao,
                Gg008Contaid = entity.Gg008Contaid,
                Gg008Periodicidadeinv = entity.Gg008Periodicidadeinv,
                Gg008ControlaSaldo = entity.Gg008ControlaSaldo,
                Gg008ControleLote = entity.Gg008ControleLote,
                Gg008ControleGrade = entity.Gg008ControleGrade,
                Gg008Anuente = entity.Gg008Anuente,
                Gg008Restricao = entity.Gg008Restricao,
                Gg008Grupocomprasid = entity.Gg008Grupocomprasid,
                Gg008Permsldnegativo = entity.Gg008Permsldnegativo,
                Gg008Minutaautomatica = entity.Gg008Minutaautomatica,
                Gg008Requisautomatica = entity.Gg008Requisautomatica,
                Gg008DataDesativacao = entity.Gg008DataDesativacao,
                Gg008Localizfixa = entity.Gg008Localizfixa,
                Gg008Diversos = entity.Gg008Diversos,
                Gg008AliqDifPis = entity.Gg008AliqDifPis,
                Gg008AliqDifCofins = entity.Gg008AliqDifCofins,
                Gg008EanTributavel = entity.Gg008EanTributavel,
                Gg008Untributavelid = entity.Gg008Untributavelid,
                Gg008FatorUnidade = entity.Gg008FatorUnidade,
                Gg008ValorPis = entity.Gg008ValorPis,
                Gg008ValorCofins = entity.Gg008ValorCofins,
                Gg008IsActive = entity.Gg008IsActive,
                Gg008TipoConversaoId = entity.Gg008TipoConversaoId,
                Gg008TipoprazoId = entity.Gg008TipoprazoId,
                Gg008TpContribuicaoId = entity.Gg008TpContribuicaoId,
                Gg008RiControlequalidade = entity.Gg008RiControlequalidade,
                Gg008AliquotaIrpj = entity.Gg008AliquotaIrpj,
                Gg008RetencaoAliqInss = entity.Gg008RetencaoAliqInss,
                Gg008RetencaoAliqIrrf = entity.Gg008RetencaoAliqIrrf,
                Gg008DescontoSuframa = entity.Gg008DescontoSuframa,
                Gg008Timestamp = entity.Gg008Timestamp,
                Gg008Plucro = entity.Gg008Plucro,
                Gg008IsctrlGondola = entity.Gg008IsctrlGondola,
                Gg008Qmediaconsumo = entity.Gg008Qmediaconsumo,
                Gg008Vmediaconsumo = entity.Gg008Vmediaconsumo,
                Gg008Dtultprocle = entity.Gg008Dtultprocle,
                Gg008VuncompraCmedio = entity.Gg008VuncompraCmedio,
                Gg008VuncompraReposicao = entity.Gg008VuncompraReposicao,
                Gg008VuncompraPrcvenda = entity.Gg008VuncompraPrcvenda,
                Gg008VuncompraPrcmercado = entity.Gg008VuncompraPrcmercado,
                Gg008VuncompraPrccusto = entity.Gg008VuncompraPrccusto,
                Gg008VuncompraCustoreal = entity.Gg008VuncompraCustoreal,
                Gg008VuncompraVlrmarglucro = entity.Gg008VuncompraVlrmarglucro,
                Gg008Moedaid = entity.Gg008Moedaid,
                Gg008Vmoeda = entity.Gg008Vmoeda,
                Gg008Prcecommerce = entity.Gg008Prcecommerce,
                Gg008Auditasn = entity.Gg008Auditasn,
                Gg008Possuisaldo = entity.Gg008Possuisaldo,
                Gg008Ultrecebimento = entity.Gg008Ultrecebimento,
                Gg008Qtdultrecebto = entity.Gg008Qtdultrecebto,
                Gg008UltimaVenda = entity.Gg008UltimaVenda,
                Gg008QtdeUltVenda = entity.Gg008QtdeUltVenda,
                Gg008TpcbarratribId = entity.Gg008TpcbarratribId
            };
        }

        public static DtoGetGG008Kdx_Simples ToDtoGetSimples(this CSICP_GG008Kdx entity)
        {
            return new DtoGetGG008Kdx_Simples
            {
                TenantId = entity.TenantId,
                Gg008Kardexid = entity.Gg008Kardexid,
                Gg008Filialid = entity.Gg008Filialid,
                Gg008Produtoid = entity.Gg008Produtoid,
                Gg008Codalmoxpadrao = entity.Gg008Codalmoxpadrao,
                Gg008Codalmtransf = entity.Gg008Codalmtransf,
                Gg008Almoxpadraoid = entity.Gg008Almoxpadraoid,
                Gg008Almoxtransfid = entity.Gg008Almoxtransfid,
                Gg008Unidade = entity.Gg008Unidade,
                Gg008Unidsecundaria = entity.Gg008Unidsecundaria,
                Gg008Unvendavarejoid = entity.Gg008Unvendavarejoid,
                Gg008Uncompravarejoid = entity.Gg008Uncompravarejoid,
                Gg008Unvendaatacadoid = entity.Gg008Unvendaatacadoid,
                Gg008FatorConversao = entity.Gg008FatorConversao,
                Gg008AliquotaIpi = entity.Gg008AliquotaIpi,
                Gg008AliquotaIcms = entity.Gg008AliquotaIcms,
                Gg008AliqIcmsReduzidaPdv = entity.Gg008AliqIcmsReduzidaPdv,
                Gg008AliquotaIss = entity.Gg008AliquotaIss,
                Gg008Margemlucrosai = entity.Gg008Margemlucrosai,
                Gg008Margemlucroent = entity.Gg008Margemlucroent,
                Gg008CalculaIrrf = entity.Gg008CalculaIrrf,
                Gg008CalculaInss = entity.Gg008CalculaInss,
                Gg008PercCsll = entity.Gg008PercCsll,
                Gg008PercCofins = entity.Gg008PercCofins,
                Gg008PercPis = entity.Gg008PercPis,
                Gg008IcmsPauta = entity.Gg008IcmsPauta,
                Gg008IpiPauta = entity.Gg008IpiPauta,
                Gg008Qtdpedidocompra = entity.Gg008Qtdpedidocompra,
                Gg008EstoqueMinimo = entity.Gg008EstoqueMinimo,
                Gg008EstoqueMaximo = entity.Gg008EstoqueMaximo,
                Gg008TempoReposicao = entity.Gg008TempoReposicao,
                Gg008PontoPedido = entity.Gg008PontoPedido,
                Gg008LoteEconomico = entity.Gg008LoteEconomico,
                Gg008GrauAtendimento = entity.Gg008GrauAtendimento,
                Gg008PercTolerancia = entity.Gg008PercTolerancia,
                Gg008Abc = entity.Gg008Abc,
                Gg008PercComissao = entity.Gg008PercComissao,
                Gg008DataFabricacao = entity.Gg008DataFabricacao,
                Gg008DataValidade = entity.Gg008DataValidade,
                Gg008DiasValidade = entity.Gg008DiasValidade,
                Gg008CustoMedio = entity.Gg008CustoMedio,
                Gg008PrecoReposicao = entity.Gg008PrecoReposicao,
                Gg008PercDescItem = entity.Gg008PercDescItem,
                Gg008Prcpromocional = entity.Gg008Prcpromocional,
                Gg008QtdPromocional = entity.Gg008QtdPromocional,
                Gg008FatorLucro = entity.Gg008FatorLucro,
                Gg008PrcVendavarejo = entity.Gg008PrcVendavarejo,
                Gg008PrcVndMercado = entity.Gg008PrcVndMercado,
                Gg008Ultreajprcvenda = entity.Gg008Ultreajprcvenda,
                Gg008PrecoVendaLiq = entity.Gg008PrecoVendaLiq,
                Gg008Vlrmargemlucro = entity.Gg008Vlrmargemlucro,
                Gg008Alteraprcvenda = entity.Gg008Alteraprcvenda,
                Gg008PrecoCusto = entity.Gg008PrecoCusto,
                Gg008Ultreajprccusto = entity.Gg008Ultreajprccusto,
                Gg008PrecoCustoReal = entity.Gg008PrecoCustoReal,
                Gg008CentroCusto = entity.Gg008CentroCusto,
                Gg008Ccustoid = entity.Gg008Ccustoid,
                Gg008ContaContabil = entity.Gg008ContaContabil,
                Gg008ClasseContabil = entity.Gg008ClasseContabil,
                Gg008FornecedorCanal = entity.Gg008FornecedorCanal,
                Gg008Fornecedorpadrao = entity.Gg008Fornecedorpadrao,
                Gg008Contaid = entity.Gg008Contaid,
                Gg008Periodicidadeinv = entity.Gg008Periodicidadeinv,
                Gg008ControlaSaldo = entity.Gg008ControlaSaldo,
                Gg008ControleLote = entity.Gg008ControleLote,
                Gg008ControleGrade = entity.Gg008ControleGrade,
                Gg008Anuente = entity.Gg008Anuente,
                Gg008Restricao = entity.Gg008Restricao,
                Gg008Grupocomprasid = entity.Gg008Grupocomprasid,
                Gg008Permsldnegativo = entity.Gg008Permsldnegativo,
                Gg008Minutaautomatica = entity.Gg008Minutaautomatica,
                Gg008Requisautomatica = entity.Gg008Requisautomatica,
                Gg008DataDesativacao = entity.Gg008DataDesativacao,
                Gg008Localizfixa = entity.Gg008Localizfixa,
                Gg008Diversos = entity.Gg008Diversos,
                Gg008AliqDifPis = entity.Gg008AliqDifPis,
                Gg008AliqDifCofins = entity.Gg008AliqDifCofins,
                Gg008EanTributavel = entity.Gg008EanTributavel,
                Gg008Untributavelid = entity.Gg008Untributavelid,
                Gg008FatorUnidade = entity.Gg008FatorUnidade,
                Gg008ValorPis = entity.Gg008ValorPis,
                Gg008ValorCofins = entity.Gg008ValorCofins,
                Gg008IsActive = entity.Gg008IsActive,
                Gg008TipoConversaoId = entity.Gg008TipoConversaoId,
                Gg008TipoprazoId = entity.Gg008TipoprazoId,
                Gg008TpContribuicaoId = entity.Gg008TpContribuicaoId,
                Gg008RiControlequalidade = entity.Gg008RiControlequalidade,
                Gg008AliquotaIrpj = entity.Gg008AliquotaIrpj,
                Gg008RetencaoAliqInss = entity.Gg008RetencaoAliqInss,
                Gg008RetencaoAliqIrrf = entity.Gg008RetencaoAliqIrrf,
                Gg008DescontoSuframa = entity.Gg008DescontoSuframa,
                Gg008Timestamp = entity.Gg008Timestamp,
                Gg008Plucro = entity.Gg008Plucro,
                Gg008IsctrlGondola = entity.Gg008IsctrlGondola,
                Gg008Qmediaconsumo = entity.Gg008Qmediaconsumo,
                Gg008Vmediaconsumo = entity.Gg008Vmediaconsumo,
                Gg008Dtultprocle = entity.Gg008Dtultprocle,
                Gg008VuncompraCmedio = entity.Gg008VuncompraCmedio,
                Gg008VuncompraReposicao = entity.Gg008VuncompraReposicao,
                Gg008VuncompraPrcvenda = entity.Gg008VuncompraPrcvenda,
                Gg008VuncompraPrcmercado = entity.Gg008VuncompraPrcmercado,
                Gg008VuncompraPrccusto = entity.Gg008VuncompraPrccusto,
                Gg008VuncompraCustoreal = entity.Gg008VuncompraCustoreal,
                Gg008VuncompraVlrmarglucro = entity.Gg008VuncompraVlrmarglucro,
                Gg008Moedaid = entity.Gg008Moedaid,
                Gg008Vmoeda = entity.Gg008Vmoeda,
                Gg008Prcecommerce = entity.Gg008Prcecommerce,
                Gg008Auditasn = entity.Gg008Auditasn,
                Gg008Possuisaldo = entity.Gg008Possuisaldo,
                Gg008Ultrecebimento = entity.Gg008Ultrecebimento,
                Gg008Qtdultrecebto = entity.Gg008Qtdultrecebto,
                Gg008UltimaVenda = entity.Gg008UltimaVenda,
                Gg008QtdeUltVenda = entity.Gg008QtdeUltVenda,
                Gg008TpcbarratribId = entity.Gg008TpcbarratribId
            };
        }

        public static DtoGetGG008KdxPrecos ToDtoGetPrecos(this CSICP_GG008Kdx entity)
        {
            return new DtoGetGG008KdxPrecos
            {
                TenantId = entity.TenantId,
                Gg008Kardexid = entity.Gg008Kardexid,
                Gg008PrecoReposicao = entity.Gg008PrecoReposicao,
                Gg008PrcVendavarejo = entity.Gg008PrcVendavarejo,
                Gg008Prcpromocional = entity.Gg008Prcpromocional ?? 0,
                Gg008PrecoCusto = entity.Gg008PrecoCusto,
                Gg008Prcecommerce = entity.Gg008Prcecommerce ?? 0,
                Gg008PrecoCustoReal = entity.Gg008PrecoCustoReal,
                NavBB001Simples = entity.NavBB001Filial?.ToDtoGetSimples(),
                NavGG008PrecosTabela = entity.NavGG008pOutrosPrecos?.ToDtoGet(),
                //NavListGG520Saldos = entity.CS_NavListaSaldos?.Select(e => e.ToDtoGetExibicao()).ToList() ?? [],
            };
        }

        public static DtoGetGG008KdxPrecos_2 ToDtoGetPrecosEstabelecimentoLogado(this CSICP_GG008Kdx entity)
        {
            return new DtoGetGG008KdxPrecos_2
            {
                TenantId = entity.TenantId,
                Gg008Kardexid = entity.Gg008Kardexid,
                Gg008PrecoReposicao = entity.Gg008PrecoReposicao,
                Gg008PrcVendavarejo = entity.Gg008PrcVendavarejo,
                Gg008Prcpromocional = entity.Gg008Prcpromocional ?? 0,
                Gg008PrecoCusto = entity.Gg008PrecoCusto,
                Gg008Prcecommerce = entity.Gg008Prcecommerce ?? 0,
                Gg008PrecoCustoReal = entity.Gg008PrecoCustoReal,

                NavGG008PrecosTabela = entity.NavGG008pOutrosPrecos?.ToDtoGet(),

            };
        }
    }
}
