using CSBS101._82Application.Mapper.BB00X.BB00X.BB001;
using CSCore.Application.Dto.Dtos;
using CSCore.Application.Dto.Dtos.Materiais_GG.GG00X.GG008;
using CSCore.Application.Dto.Mapper.GG00X;
using CSCore.Application.Dto.Mapper.Sistema;
using CSCore.Domain.CS_Models.CSICP_GG;
using CSSY103.C82Application.Mapper;
using GG104Materiais.C82Application.Dto.GG00X.GG008;

namespace GG104Materiais.C82Application.Mapper.GG008
{
    public static class GG008Mapper
    {
        public static DtoGetGG008 ToDtoGet(this CSICP_GG008 entity)
        {
            return new DtoGetGG008
            {
                TenantId = entity.TenantId,
                Id = entity.Id,
                Gg008Filialid = entity.Gg008Filialid,
                Gg008Filial = entity.Gg008Filial,
                Gg008Codgproduto = entity.Gg008Codgproduto,
                Gg008TipoProduto = entity.Gg008TipoProduto,
                Gg008CodigoGrupo = entity.Gg008CodigoGrupo,
                Gg008CodigoClasse = entity.Gg008CodigoClasse,
                Gg008CodigoArtigo = entity.Gg008CodigoArtigo,
                Gg008CodigoMarca = entity.Gg008CodigoMarca,
                Gg008CodigoPadrao = entity.Gg008CodigoPadrao,
                Gg008CodigoTipo = entity.Gg008CodigoTipo,
                Gg008CodigoQualidade = entity.Gg008CodigoQualidade,
                Gg008Tipoprodutoid = entity.Gg008Tipoprodutoid,
                Gg008Grupoid = entity.Gg008Grupoid,
                Gg008Subgrupoid = entity.Gg008Subgrupoid,
                Gg008Classeid = entity.Gg008Classeid,
                Gg008Artigoid = entity.Gg008Artigoid,
                Gg008Marcaid = entity.Gg008Marcaid,
                Gg008Linhaid = entity.Gg008Linhaid,
                Gg008Padraoid = entity.Gg008Padraoid,
                Gg008Tipoid = entity.Gg008Tipoid,
                Gg008Qualidadeid = entity.Gg008Qualidadeid,
                Gg008Referencia = entity.Gg008Referencia,
                Gg008Complemento = entity.Gg008Complemento,
                Gg008Codindustrial = entity.Gg008Codindustrial,
                Gg008Safradiamesinicio = entity.Gg008Safradiamesinicio,
                Gg008SafraDiamesfim = entity.Gg008SafraDiamesfim,
                Gg008Etiqueta = entity.Gg008Etiqueta,
                Gg008Ncm = entity.Gg008Ncm,
                Gg008ExNcm = entity.Gg008ExNcm,
                Gg008Ncmid = entity.Gg008Ncmid,
                Gg008PesoBruto = entity.Gg008PesoBruto,
                Gg008PesoLiquido = entity.Gg008PesoLiquido,
                Gg008Tamanho = entity.Gg008Tamanho,
                Gg008Largura = entity.Gg008Largura,
                Gg008Espessura = entity.Gg008Espessura,
                Gg008Embalagem1 = entity.Gg008Embalagem1,
                Gg008Embalagem2 = entity.Gg008Embalagem2,
                Gg008QtdEmbalagem1 = entity.Gg008QtdEmbalagem1,
                Gg008QtdEmbalagem2 = entity.Gg008QtdEmbalagem2,
                Gg008Comprimentoarmaz = entity.Gg008Comprimentoarmaz,
                Gg008LarguraArmaz = entity.Gg008LarguraArmaz,
                Gg008AlturaArmaz = entity.Gg008AlturaArmaz,
                Gg008FatorArmaz = entity.Gg008FatorArmaz,
                Gg008Empilhagem = entity.Gg008Empilhagem,
                Gg008Descreduzida = entity.Gg008Descreduzida,
                Gg008UsaNroSerie = entity.Gg008UsaNroSerie,
                Gg008Refersimilar = entity.Gg008Refersimilar,
                Gg008Przgarancompra = entity.Gg008Przgarancompra,
                Gg008Przgaranvenda = entity.Gg008Przgaranvenda,
                Gg008Servico = entity.Gg008Servico,
                Gg008Montavel = entity.Gg008Montavel,
                Gg008Classifvegetal = entity.Gg008Classifvegetal,
                Gg008IsActive = entity.Gg008IsActive,
                Gg008EstadofisicoId = entity.Gg008EstadofisicoId,
                Gg008TpgarantiacompraId = entity.Gg008TpgarantiacompraId,
                Gg008TpgarantiavendaId = entity.Gg008TpgarantiavendaId,
                Gg008TipokitId = entity.Gg008TipokitId,
                Gg008PesavelId = entity.Gg008PesavelId,
                Gg008Isforalinha = entity.Gg008Isforalinha,
                Gg008Dataforalinha = entity.Gg008Dataforalinha,
                Gg008ListservicoId = entity.Gg008ListservicoId,
                Gg008Grpsubgrupoid = entity.Gg008Grpsubgrupoid,
                Gg008Sequence = entity.Gg008Sequence,
                Gg008Dultalteracao = entity.Gg008Dultalteracao,
                Gg008Entregar = entity.Gg008Entregar,
                Gg008Isecommerce = entity.Gg008Isecommerce,
                Gg008AnpId = entity.Gg008AnpId,
                Gg008Dregistro = entity.Gg008Dregistro,
                Gg008Usuariopropid = entity.Gg008Usuariopropid,
                Gg008Usuarioaltid = entity.Gg008Usuarioaltid,
                Gg008Ierelevanteid = entity.Gg008Ierelevanteid,
                Gg008Cnpjfabricante = entity.Gg008Cnpjfabricante,
                Gg008Nomefabricante = entity.Gg008Nomefabricante,
                Gg008Vicmsproprio = entity.Gg008Vicmsproprio,
                NavFilialBB001 = entity.NavFilialBB001?.ToDtoGetSimples(),
                NavTipodeProdutosGG002 = entity.NavTipodeProdutosGG002?.ToDtoGet(),
                NavGrupoProdutoGG003 = entity.NavGrupoProdutoGG003?.ToDtoGetSimples(),
                NavClasseProdutoGG004 = entity.NavClasseProdutoGG004?.ToDtoGetSemFilial(),
                NavArtigoProdutoGG005 = entity.NavArtigoProdutoGG005?.ToDtoGetSemFilial(),
                NavMarcaProdutoGG006 = entity.NavMarcaProdutoGG006?.ToDtoGet(),
                NavPadraoProdutoGG009 = entity.NavPadraoProdutoGG009?.ToDtoGetSimples(),
                Gg008Descespecial1 = entity.Gg008Descespecial1,
                Gg008Descespecial2 = entity.Gg008Descespecial2,
                NavTipoPadraoProdutoGG010 = entity.NavTipoPadraoProdutoGG010?.ToDtoGetSimples(),
                NavQualidadeProdutoGG011 = entity.NavQualidadeProdutoGG011?.ToDtoGetSimples(),
                NavLinhaProdutoGG014 = entity.NavLinhaProdutoGG014?.ToDtoGetSimples(),
                NavNCMProdutoGG021 = entity.NavNCMProdutoGG021?.ToDtoGetSimples(),
                NavGG060_GrpSubGrupo = entity.NavGG060_GrpSubGrupo?.ToDtoGetSimples(),
                NavGG029_ANP = entity.NavGG029_ANP?.ToDtoGet(),
                NavSY001_UsuarioProp = entity.NavSY001_UsuarioProp?.ToDtoGetSimples(),
                NavSY001_UsuarioAlt = entity.NavSY001_UsuarioAlt?.ToDtoGetSimples(),
                NavGG008_EstadoFisico = entity.NavGG008_EstadoFisico,
                NavGG008_TpGarantiaCompra = entity.NavGG008_TpGarantiaCompra,
                NavGG008_TpGarantiaVenda = entity.NavGG008_TpGarantiaVenda,
                NavGG008_TipoKit = entity.NavGG008_TipoKit,
                NavGG008_ListServico = entity.NavGG008_ListServico,
                NavGG008_Etiqueta = entity.NavGG008_Etiqueta,
                NavGG008_Usa_Nro_Serie = entity.NavGG008_Usa_Nro_Serie,
                NavGG008_Servico = entity.NavGG008_Servico,
                NavGG008_Montavel = entity.NavGG008_Montavel,
                NavGG008_Pesavel = entity.NavGG008_Pesavel,
                NavGG008_Entregar = entity.NavGG008_Entregar,
                Navgg008_IERelevante = entity.Navgg008_IERelevante,
                NavSubGrupoProdutoGG015 = entity.NavSubGrupoProdutoGG015?.ToDtoGet(),
            };
        }
        public static DtoGetGG008_ComListaKardex ToDtoGetComSaldos(this RepoDtoResponseGG008Kdx entity)
        {
            return new DtoGetGG008_ComListaKardex
            {
                TenantId = entity.TenantId,
                Id = entity.Id,
                Gg008Filialid = entity.Gg008Filialid,
                Gg008Filial = entity.Gg008Filial,
                Gg008Codgproduto = entity.Gg008Codgproduto,
                Gg008TipoProduto = entity.Gg008TipoProduto,
                Gg008CodigoGrupo = entity.Gg008CodigoGrupo,
                Gg008CodigoClasse = entity.Gg008CodigoClasse,
                Gg008CodigoArtigo = entity.Gg008CodigoArtigo,
                Gg008CodigoMarca = entity.Gg008CodigoMarca,
                Gg008CodigoPadrao = entity.Gg008CodigoPadrao,
                Gg008CodigoTipo = entity.Gg008CodigoTipo,
                Gg008CodigoQualidade = entity.Gg008CodigoQualidade,
                Gg008Tipoprodutoid = entity.Gg008Tipoprodutoid,
                Gg008Grupoid = entity.Gg008Grupoid,
                Gg008Subgrupoid = entity.Gg008Subgrupoid,
                Gg008Classeid = entity.Gg008Classeid,
                Gg008Artigoid = entity.Gg008Artigoid,
                Gg008Marcaid = entity.Gg008Marcaid,
                Gg008Linhaid = entity.Gg008Linhaid,
                Gg008Padraoid = entity.Gg008Padraoid,
                Gg008Tipoid = entity.Gg008Tipoid,
                Gg008Qualidadeid = entity.Gg008Qualidadeid,
                Gg008Referencia = entity.Gg008Referencia,
                Gg008Complemento = entity.Gg008Complemento,
                Gg008Codindustrial = entity.Gg008Codindustrial,
                Gg008Safradiamesinicio = entity.Gg008Safradiamesinicio,
                Gg008SafraDiamesfim = entity.Gg008SafraDiamesfim,
                Gg008Etiqueta = entity.Gg008Etiqueta,
                Gg008Ncm = entity.Gg008Ncm,
                Gg008ExNcm = entity.Gg008ExNcm,
                Gg008Ncmid = entity.Gg008Ncmid,
                Gg008PesoBruto = entity.Gg008PesoBruto,
                Gg008PesoLiquido = entity.Gg008PesoLiquido,
                Gg008Tamanho = entity.Gg008Tamanho,
                Gg008Largura = entity.Gg008Largura,
                Gg008Espessura = entity.Gg008Espessura,
                Gg008Embalagem1 = entity.Gg008Embalagem1,
                Gg008Embalagem2 = entity.Gg008Embalagem2,
                Gg008QtdEmbalagem1 = entity.Gg008QtdEmbalagem1,
                Gg008QtdEmbalagem2 = entity.Gg008QtdEmbalagem2,
                Gg008Comprimentoarmaz = entity.Gg008Comprimentoarmaz,
                Gg008LarguraArmaz = entity.Gg008LarguraArmaz,
                Gg008AlturaArmaz = entity.Gg008AlturaArmaz,
                Gg008FatorArmaz = entity.Gg008FatorArmaz,
                Gg008Empilhagem = entity.Gg008Empilhagem,
                Gg008Descreduzida = entity.Gg008Descreduzida,
                Gg008UsaNroSerie = entity.Gg008UsaNroSerie,
                Gg008Refersimilar = entity.Gg008Refersimilar,
                Gg008Przgarancompra = entity.Gg008Przgarancompra,
                Gg008Przgaranvenda = entity.Gg008Przgaranvenda,
                Gg008Servico = entity.Gg008Servico,
                Gg008Montavel = entity.Gg008Montavel,
                Gg008Classifvegetal = entity.Gg008Classifvegetal,
                Gg008IsActive = entity.Gg008IsActive,
                Gg008EstadofisicoId = entity.Gg008EstadofisicoId,
                Gg008TpgarantiacompraId = entity.Gg008TpgarantiacompraId,
                Gg008TpgarantiavendaId = entity.Gg008TpgarantiavendaId,
                Gg008TipokitId = entity.Gg008TipokitId,
                Gg008PesavelId = entity.Gg008PesavelId,
                Gg008Isforalinha = entity.Gg008Isforalinha,
                Gg008Dataforalinha = entity.Gg008Dataforalinha,
                Gg008ListservicoId = entity.Gg008ListservicoId,
                Gg008Grpsubgrupoid = entity.Gg008Grpsubgrupoid,
                Gg008Sequence = entity.Gg008Sequence,
                Gg008Dultalteracao = entity.Gg008Dultalteracao,
                Gg008Entregar = entity.Gg008Entregar,
                Gg008Isecommerce = entity.Gg008Isecommerce,
                Gg008AnpId = entity.Gg008AnpId,
                Gg008Dregistro = entity.Gg008Dregistro,
                Gg008Usuariopropid = entity.Gg008Usuariopropid,
                Gg008Usuarioaltid = entity.Gg008Usuarioaltid,
                Gg008Ierelevanteid = entity.Gg008Ierelevanteid,
                Gg008Cnpjfabricante = entity.Gg008Cnpjfabricante,
                Gg008Nomefabricante = entity.Gg008Nomefabricante,
                Gg008Vicmsproprio = entity.Gg008Vicmsproprio,
                Gg008Descespecial1 = entity.Gg008Descespecial1,
                Gg008Descespecial2 = entity.Gg008Descespecial2,
                CS_KardexId = entity.CS_KardexId,
                //INCLUDES ABAIXO
                NavGG008cCaracteristica = entity.CS_NavCaracteristica?.ToDtoGet(),
                NavGG008cFichaTecnica = entity.CS_NavFichaTecnica?.ToDtoGet(),
                NavListGG008cImagens = entity.CS_NavListImagens?.Select(x => x.ToDtoGet()),
                NavFilialBB001 = entity.NavFilialBB001?.ToDtoGetSimples(),
                NavTipodeProdutosGG002 = entity.NavTipodeProdutosGG002?.ToDtoGet(),
                NavGrupoProdutoGG003 = entity.NavGrupoProdutoGG003?.ToDtoGetSimples(),
                NavClasseProdutoGG004 = entity.NavClasseProdutoGG004?.ToDtoGetSemFilial(),
                NavArtigoProdutoGG005 = entity.NavArtigoProdutoGG005?.ToDtoGetSemFilial(),
                NavMarcaProdutoGG006 = entity.NavMarcaProdutoGG006?.ToDtoGet(),
                NavPadraoProdutoGG009 = entity.NavPadraoProdutoGG009?.ToDtoGetSimples(),
                NavTipoPadraoProdutoGG010 = entity.NavTipoPadraoProdutoGG010?.ToDtoGetSimples(),
                NavQualidadeProdutoGG011 = entity.NavQualidadeProdutoGG011?.ToDtoGetSimples(),
                NavLinhaProdutoGG014 = entity.NavLinhaProdutoGG014?.ToDtoGetSimples(),
                NavNCMProdutoGG021 = entity.NavNCMProdutoGG021?.ToDtoGetSimples(),

                NavSubGrupoProdutoGG015 = entity.NavSubGrupoProdutoGG015?.ToDtoGet(),
                CS_SaldoTotal = entity.CS_SaldoTotal,
                CS_EstabelecimentoLogadoPrecos = entity.CS_EstabelecimentoLogadoPrecos?.ToDtoGetPrecosEstabelecimentoLogado(),
            };
        }

        public static DtoGetGG008Simples ToDtoGetSimples(this CSICP_GG008 entity)
        {
            return new DtoGetGG008Simples
            {
                TenantId = entity.TenantId,
                Id = entity.Id,
                Gg008Filialid = entity.Gg008Filialid,
                Gg008Filial = entity.Gg008Filial,
                Gg008Codgproduto = entity.Gg008Codgproduto,
                Gg008TipoProduto = entity.Gg008TipoProduto,
                Gg008CodigoGrupo = entity.Gg008CodigoGrupo,
                Gg008CodigoClasse = entity.Gg008CodigoClasse,
                Gg008CodigoArtigo = entity.Gg008CodigoArtigo,
                Gg008CodigoMarca = entity.Gg008CodigoMarca,
                Gg008CodigoPadrao = entity.Gg008CodigoPadrao,
                Gg008CodigoTipo = entity.Gg008CodigoTipo,
                Gg008CodigoQualidade = entity.Gg008CodigoQualidade,
                Gg008Tipoprodutoid = entity.Gg008Tipoprodutoid,
                Gg008Grupoid = entity.Gg008Grupoid,
                Gg008Subgrupoid = entity.Gg008Subgrupoid,
                Gg008Classeid = entity.Gg008Classeid,
                Gg008Artigoid = entity.Gg008Artigoid,
                Gg008Marcaid = entity.Gg008Marcaid,
                Gg008Linhaid = entity.Gg008Linhaid,
                Gg008Padraoid = entity.Gg008Padraoid,
                Gg008Tipoid = entity.Gg008Tipoid,
                Gg008Qualidadeid = entity.Gg008Qualidadeid,
                Gg008Referencia = entity.Gg008Referencia,
                Gg008Complemento = entity.Gg008Complemento,
                Gg008Codindustrial = entity.Gg008Codindustrial,
                Gg008Safradiamesinicio = entity.Gg008Safradiamesinicio,
                Gg008SafraDiamesfim = entity.Gg008SafraDiamesfim,
                Gg008Etiqueta = entity.Gg008Etiqueta,
                Gg008Ncm = entity.Gg008Ncm,
                Gg008ExNcm = entity.Gg008ExNcm,
                Gg008Ncmid = entity.Gg008Ncmid,
                Gg008PesoBruto = entity.Gg008PesoBruto,
                Gg008PesoLiquido = entity.Gg008PesoLiquido,
                Gg008Tamanho = entity.Gg008Tamanho,
                Gg008Largura = entity.Gg008Largura,
                Gg008Espessura = entity.Gg008Espessura,
                Gg008Embalagem1 = entity.Gg008Embalagem1,
                Gg008Embalagem2 = entity.Gg008Embalagem2,
                Gg008QtdEmbalagem1 = entity.Gg008QtdEmbalagem1,
                Gg008QtdEmbalagem2 = entity.Gg008QtdEmbalagem2,
                Gg008Comprimentoarmaz = entity.Gg008Comprimentoarmaz,
                Gg008LarguraArmaz = entity.Gg008LarguraArmaz,
                Gg008AlturaArmaz = entity.Gg008AlturaArmaz,
                Gg008FatorArmaz = entity.Gg008FatorArmaz,
                Gg008Empilhagem = entity.Gg008Empilhagem,
                Gg008Descreduzida = entity.Gg008Descreduzida,
                Gg008UsaNroSerie = entity.Gg008UsaNroSerie,
                Gg008Refersimilar = entity.Gg008Refersimilar,
                Gg008Przgarancompra = entity.Gg008Przgarancompra,
                Gg008Przgaranvenda = entity.Gg008Przgaranvenda,
                Gg008Servico = entity.Gg008Servico,
                Gg008Montavel = entity.Gg008Montavel,
                Gg008Classifvegetal = entity.Gg008Classifvegetal,
                Gg008IsActive = entity.Gg008IsActive,
                Gg008EstadofisicoId = entity.Gg008EstadofisicoId,
                Gg008TpgarantiacompraId = entity.Gg008TpgarantiacompraId,
                Gg008TpgarantiavendaId = entity.Gg008TpgarantiavendaId,
                Gg008PesavelId = entity.Gg008PesavelId,
                Gg008Isforalinha = entity.Gg008Isforalinha,
                Gg008Dataforalinha = entity.Gg008Dataforalinha,
                Gg008ListservicoId = entity.Gg008ListservicoId,
                Gg008Grpsubgrupoid = entity.Gg008Grpsubgrupoid,
                Gg008Sequence = entity.Gg008Sequence,
                Gg008Dultalteracao = entity.Gg008Dultalteracao,
                Gg008Entregar = entity.Gg008Entregar,
                Gg008Isecommerce = entity.Gg008Isecommerce,
                Gg008AnpId = entity.Gg008AnpId,
                Gg008Dregistro = entity.Gg008Dregistro,
                Gg008Usuariopropid = entity.Gg008Usuariopropid,
                Gg008Usuarioaltid = entity.Gg008Usuarioaltid,
                Gg008Ierelevanteid = entity.Gg008Ierelevanteid,
                Gg008Cnpjfabricante = entity.Gg008Cnpjfabricante,
                Gg008Nomefabricante = entity.Gg008Nomefabricante,
                Gg008Vicmsproprio = entity.Gg008Vicmsproprio,
                //Gg008Descpeqwms1 = entity.Gg008Descpeqwms1,
                //Gg008Descpeqwms2 = entity.Gg008Descpeqwms2,
                Gg008Descespecial1 = entity.Gg008Descespecial1,
                Gg008Descespecial2 = entity.Gg008Descespecial2,
                CS_GG015SubGrupo_Label = entity.NavSubGrupoProdutoGG015?.Gg015Subgrupo,

            };
        }

        public static DtoGetGG008_Exibicao_Simples ToDtoGetExibicaoSimples(this CSICP_GG008 entity)
        {
            return new DtoGetGG008_Exibicao_Simples
            {
                TenantId = entity.TenantId,
                Id = entity.Id,

                Gg008Codgproduto = entity.Gg008Codgproduto,

                Gg008Descreduzida = entity.Gg008Descreduzida,


            };
        }
    }
}

