# name: Chamar Producao

# on:
#   push:
#     branches:
#       - main

# jobs:
#   trigger-wsite-dsv17:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Checa API
#         run: |
#           CURRENT_DATE=$(date +"%Y.%m.%d")  # Formato YYYY.MM.DD (sem hora)
#           curl -X POST \
#           -H "Accept: application/vnd.github.v3+json" \
#           -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN_GITHUB }}" \
#           https://api.github.com/repos/CS-CONSOFT/CS_Publish/actions/workflows/002_GerarVersaoAPI_PROD.yml/dispatches \
#           -d '{"ref":"main", "inputs": {"versao": "'"$CURRENT_DATE"'", "produto":"materiais"}}'