name: Chamar Pre Release

on:
  push:
    branches:
      - release

jobs:
  trigger-wsite-dsv17:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Checa API
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN_GITHUB }}" \
          https://api.github.com/repos/CS-CONSOFT/CS_Publish/actions/workflows/02_1_PreRelease_ChecaAPI.yml/dispatches \
          -d '{"ref":"main"}'