name: Deploy e AutoMerge Workflow

on:
  push:
    branches:
      - 'dev_**'

jobs:
  automerge-dev-branch:
    if: startsWith(github.ref, 'refs/heads/dev_')
    runs-on: ubuntu-latest
    steps:
      - name: Extrair nome da branch
        id: branch_name
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

      - name: Criar Pull Request para develop
        id: criar_pr
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.CS_ACCESS_TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/CS-CONSOFT/CSLB900_Cores/pulls \
            -d "{
                  \"title\": \"Auto merge: ${{ steps.branch_name.outputs.branch_name }} -> develop\",
                  \"body\": \"Merge automático da branch ${{ steps.branch_name.outputs.branch_name }} para develop\",
                  \"head\": \"${{ steps.branch_name.outputs.branch_name }}\",
                  \"base\": \"develop\"
                }")
          pr_number=$(echo "$response" | jq -r '.number')
          echo "PR Number: $pr_number"
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT

      - name: Aprovar PR via API
        if: ${{ steps.criar_pr.outputs.pr_number != '' && steps.criar_pr.outputs.pr_number != 'null' }}
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.CS_ACCESS_TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/CS-CONSOFT/CSLB900_Cores/pulls/${{ steps.criar_pr.outputs.pr_number }}/reviews \
            -d '{"event":"APPROVE"}'

      - name: Merge PR via API
        if: ${{ steps.criar_pr.outputs.pr_number != '' && steps.criar_pr.outputs.pr_number != 'null' }}
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.CS_ACCESS_TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/CS-CONSOFT/CSLB900_Cores/pulls/${{ steps.criar_pr.outputs.pr_number }}/merge \
            -d '{"merge_method":"merge"}'